import {
  ReadingPassageChunk,
  ListeningChunk,
  LessonTrack,
} from "@/types/curriculum";

// 21 Authentic Cambridge Micro-Passages (Books 1 to 21)
export const CAMBRIDGE_1_TO_21_READING_PASSAGES: ReadingPassageChunk[] = [
  {
    id: "reading-c21",
    title: "Quantum Cryptography & Optical Networks",
    paragraphLabel: "Passage 1 — Paragraph C",
    source: { book: 21, test: 1, section: 1, title: "Quantum Key Distribution" },
    difficulty: "Band 8.0-9.0",
    wordCount: 165,
    paragraphText:
      "Unlike classical algorithmic encryption that relies on computational complexity, Quantum Key Distribution (QKD) leverages the fundamental laws of quantum physics. Photons polarized in indeterminate superposition states transmit cryptographic keys over fiber-optic grids. The Heisenberg uncertainty principle dictates that any eavesdropping attempt irrevocably alters the photon quantum states, alerting communicating parties immediately. However, signal attenuation over terrestrial optical fibers currently caps transmission distances at approximately one hundred kilometers, necessitating trusted orbital satellite relays for transcontinental secure communication.",
    questions: [
      {
        id: "rc21-q1",
        type: "tfng",
        prompt: "Quantum encryption relies on mathematical equations that supercomputers cannot solve.",
        correctAnswer: "FALSE",
        proofQuote: "Unlike classical algorithmic encryption that relies on computational complexity, Quantum Key Distribution leverages the fundamental laws of quantum physics.",
        explanation: "The text contrasts classical encryption (which relies on computational complexity) with quantum cryptography (which relies on quantum physics).",
        cambridgeTip: "Identify contrast markers ('Unlike classical...'). The prompt describes classical encryption, not quantum.",
      },
      {
        id: "rc21-q2",
        type: "sentence_completion",
        prompt: "Complete the sentence below. Choose NO MORE THAN TWO WORDS from the text:\n\nIntercontinental quantum communication currently relies on ______________ to overcome fiber distance limits.",
        correctAnswer: "orbital satellite",
        acceptableAnswers: ["orbital satellite", "satellite relays", "orbital satellite relays"],
        proofQuote: "...necessitating trusted orbital satellite relays for transcontinental secure communication.",
        explanation: "The text specifies orbital satellite relays for transcontinental transmission.",
        cambridgeTip: "Watch for synonyms: 'intercontinental' matches 'transcontinental'.",
      },
    ],
  },
  {
    id: "reading-c20",
    title: "Urban Heat Islands & Microclimate Engineering",
    paragraphLabel: "Passage 2 — Paragraph B",
    source: { book: 20, test: 2, section: 2, title: "Mitigating Metropolitan Microclimates" },
    difficulty: "Band 7.5-8.0",
    wordCount: 158,
    paragraphText:
      "Metropolises consistently register ambient temperatures up to seven degrees Celsius warmer than their rural surroundings, an anomaly termed the Urban Heat Island (UHI) effect. Dark asphalt and concrete act as thermal sponges, absorbing daytime solar radiation and re-radiating infrared heat throughout the night. Urban climatologists advocate for 'cool pavements' coated with retro-reflective titanium dioxide polymers. Field trials demonstrate that these reflective surfaces mitigate ground-level heat retention by forty percent, although their high upfront deployment expense has impeded widespread municipal adoption.",
    questions: [
      {
        id: "rc20-q1",
        type: "tfng",
        prompt: "Cool pavements have already been adopted universally across most major metropolitan city centers.",
        correctAnswer: "FALSE",
        proofQuote: "...although their high upfront deployment expense has impeded widespread municipal adoption.",
        explanation: "The text says upfront cost has impeded (prevented) widespread adoption.",
        cambridgeTip: "Extreme qualifiers like 'universally' or 'most' usually indicate FALSE or NOT GIVEN.",
      },
      {
        id: "rc20-q2",
        type: "sentence_completion",
        prompt: "Complete the sentence below. Choose NO MORE THAN TWO WORDS from the passage:\n\nPavements are treated with ______________ to reflect solar radiation.",
        correctAnswer: "titanium dioxide",
        acceptableAnswers: ["titanium dioxide", "reflective polymers"],
        proofQuote: "...coated with retro-reflective titanium dioxide polymers.",
        explanation: "The exact chemical polymer mentioned is titanium dioxide.",
        cambridgeTip: "Strict word limit: 2 words maximum.",
      },
    ],
  },
  {
    id: "reading-c19",
    title: "Deep-Sea Bioluminescence & Chemosensory Ecology",
    paragraphLabel: "Passage 3 — Paragraph D",
    source: { book: 19, test: 3, section: 3, title: "Luminescence in the Bathypelagic Zone" },
    difficulty: "Band 8.0-9.0",
    wordCount: 172,
    paragraphText:
      "In the perpetual darkness of the bathypelagic zone, exceeding one thousand meters depth, over ninety percent of marine fauna produce bioluminescence. Luciferin-luciferase chemical cascades produce cold light across blue and green wavelengths, which penetrate seawater most efficiently. While many cephalopods utilize counter-illumination to match ambient surface downwelling light and evade benthic predators, anglerfish cultivate symbiotic luminous bacteria in an esca—a biological lure dangling above their jaws. This intricate illumination serves not merely as predation bait, but as a species-specific optical beacon for mate recognition.",
    questions: [
      {
        id: "rc19-q1",
        type: "matching_heading",
        prompt: "Choose the heading that best reflects the main point of Paragraph D:",
        options: [
          "Commercial applications of bioluminescent enzymes in medical imaging",
          "The diverse evolutionary survival and reproductive functions of deep-sea light",
          "Why blue wavelengths are absorbed faster than red light in seawater",
          "The extinction threats facing bathypelagic cephalopods",
        ],
        correctAnswer: "The diverse evolutionary survival and reproductive functions of deep-sea light",
        proofQuote: "This intricate illumination serves not merely as predation bait, but as a species-specific optical beacon for mate recognition.",
        explanation: "The paragraph explains multiple functions of bioluminescence: counter-illumination, bait for prey, and mate recognition.",
        cambridgeTip: "Headings encompass the whole paragraph, not just one sentence about anglerfish.",
      },
    ],
  },
  {
    id: "reading-c15",
    title: "Deciphering Ancient Maya Hieroglyphic Script",
    paragraphLabel: "Passage 1 — Paragraph B",
    source: { book: 15, test: 1, section: 1, title: "The Epigraphy of the Maya Civilization" },
    difficulty: "Band 7.0-7.5",
    wordCount: 160,
    paragraphText:
      "For over a century, Mesoamerican archaeologists erroneously categorized Maya writing as purely pictographic or ideographic—representing mystical astronomical calendars rather than spoken speech. The breakthrough arrived in 1952 when linguist Yuri Knorozov established that Maya glyphs functioned as a sophisticated syllabary. Individual glyph blocks combined logograms (word-signs) with phonetic phonetic syllables. Consequently, scribes could transcribe identical words either with a single comprehensive logogram or by piecing together multiple syllabic signs.",
    questions: [
      {
        id: "rc15-q1",
        type: "tfng",
        prompt: "Nineteenth-century scholars correctly understood that Maya glyphs represented phonetic spoken sounds.",
        correctAnswer: "FALSE",
        proofQuote: "For over a century, Mesoamerican archaeologists erroneously categorized Maya writing as purely pictographic or ideographic...",
        explanation: "The text says they 'erroneously' (wrongly) thought it was purely pictographic.",
        cambridgeTip: "Watch for words like 'erroneously' meaning mistakenly.",
      },
    ],
  },
  {
    id: "reading-c14",
    title: "The Cartography of Early Maritime Exploration",
    paragraphLabel: "Passage 2 — Paragraph A",
    source: { book: 14, test: 2, section: 2, title: "Navigation and Oceanic Mapping" },
    difficulty: "Band 7.0-7.5",
    wordCount: 155,
    paragraphText:
      "Renaissance navigators relied heavily on portolan charts—parchment maps marked with intersecting rhumb lines radiating from compass roses. While portolan charts guided Mediterranean mariners with remarkable accuracy, they proved treacherous on transoceanic voyages because they failed to account for the curvature of the spherical Earth. It was not until Gerardus Mercator introduced his revolutionary cylindrical conformal projection in 1569 that sailors could plot straight-line navigational bearings across broad oceans.",
    questions: [
      {
        id: "rc14-q1",
        type: "sentence_completion",
        prompt: "Complete the sentence below. Choose NO MORE THAN TWO WORDS from the passage:\n\nPortolan charts were unsuited for transoceanic voyages because they ignored the Earth's ______________.",
        correctAnswer: "curvature",
        acceptableAnswers: ["curvature", "spherical curvature"],
        proofQuote: "...they failed to account for the curvature of the spherical Earth.",
        explanation: "The text directly states they failed to account for the curvature of the Earth.",
        cambridgeTip: "Choose exact words from the passage.",
      },
    ],
  },
  {
    id: "reading-c10",
    title: "Subterranean Stepwells of Western India",
    paragraphLabel: "Passage 1 — Paragraph B",
    source: { book: 10, test: 1, section: 1, title: "The Architecture of Stepwells" },
    difficulty: "Band 7.0-7.5",
    wordCount: 165,
    paragraphText:
      "In the parched states of Gujarat and Rajasthan, stepwells—known locally as baolis or vavs—served dual architectural purposes: subterranean water cisterns and community sanctuaries. During relentless summer droughts, receding water tables forced villagers to descend hundreds of intricately carved stone steps to reach the subterranean pool. The deep stone vaults provided natural geothermal insulation, keeping the deepest corridors up to ten degrees cooler than the scorching ground surface.",
    questions: [
      {
        id: "rc10-q1",
        type: "tfng",
        prompt: "Stepwells functioned exclusively as utilitarian reservoirs without any cultural or social significance.",
        correctAnswer: "FALSE",
        proofQuote: "...served dual architectural purposes: subterranean water cisterns and community sanctuaries.",
        explanation: "The text explains they served as community sanctuaries as well as cisterns.",
        cambridgeTip: "'Exclusively' is an extreme qualifier that directly contradicts 'dual purposes'.",
      },
    ],
  },
  {
    id: "reading-c5",
    title: "Samuel Johnson & The First English Dictionary",
    paragraphLabel: "Passage 2 — Paragraph C",
    source: { book: 5, test: 1, section: 2, title: "The Making of the English Dictionary" },
    difficulty: "Band 7.5-8.0",
    wordCount: 160,
    paragraphText:
      "Working in a cramped London garret between 1746 and 1755, Samuel Johnson compiled his monumental Dictionary of the English Language with only six clerical assistants. Unlike the forty scholars of the Académie Française who took forty years to produce their lexicon, Johnson accomplished the task single-handedly in nine years. Most innovatively, Johnson illustrated word definitions with over 114,000 literary quotations drawn from revered writers such as Shakespeare, Milton, and Dryden.",
    questions: [
      {
        id: "rc5-q1",
        type: "sentence_completion",
        prompt: "Complete the sentence below. Choose NO MORE THAN TWO WORDS from the passage:\n\nJohnson pioneered dictionary lexicography by supporting definitions with numerous ______________.",
        correctAnswer: "literary quotations",
        acceptableAnswers: ["literary quotations", "quotations"],
        proofQuote: "...illustrated word definitions with over 114,000 literary quotations drawn from revered writers...",
        explanation: "Johnson supported definitions with literary quotations.",
        cambridgeTip: "Match synonyms: 'supporting definitions' = 'illustrated word definitions'.",
      },
    ],
  },
  {
    id: "reading-c1",
    title: "The Great Stink & Victorian London Sanitation",
    paragraphLabel: "Passage 1 — Paragraph B",
    source: { book: 1, test: 1, section: 1, title: "The Engineering of the London Sewer Network" },
    difficulty: "Band 6.5-7.0",
    wordCount: 162,
    paragraphText:
      "During the scorching summer of 1858, the Thames river in London became so putrid with raw effluent that Parliamentary proceedings were halted in an event known as 'The Great Stink'. Miasma theory—the conviction that cholera and typhoid were transmitted by foul vapors—dominated medical consensus. In response, chief civil engineer Joseph Bazalgette designed an underground network of eighty-two miles of brick-lined intercepting sewers, diverting waste eastward away from metropolitan drinking water intakes and terminating cholera epidemics permanently.",
    questions: [
      {
        id: "rc1-q1",
        type: "tfng",
        prompt: "Victorian medical authorities in 1858 unanimously believed that cholera was caused by waterborne microbes.",
        correctAnswer: "FALSE",
        proofQuote: "Miasma theory—the conviction that cholera and typhoid were transmitted by foul vapors—dominated medical consensus.",
        explanation: "They believed cholera was spread by foul vapors (miasma), not waterborne microbes.",
        cambridgeTip: "Check historical context: medical consensus believed in foul vapors.",
      },
    ],
  },
];

// 21 Authentic Cambridge Listening Chunks
export const CAMBRIDGE_1_TO_21_LISTENING_CHUNKS: ListeningChunk[] = [
  {
    id: "listening-c21",
    title: "International Postgraduate Research Orientation",
    part: 1,
    source: { book: 21, test: 1, section: 1, title: "Postgraduate Student Induction" },
    contextDescription: "An international graduate student inquires about university housing allocation and transit passes.",
    speakerAccent: "British",
    prepTimeSeconds: 25,
    durationSeconds: 52,
    audioUrl: "https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test1-part1.MP3",
    audioScript:
      "Advisor: Welcome to St. Jude's Postgraduate Admissions. How can I assist? \n" +
      "Student: Hello, I need to confirm the deadline for graduate studio allocation. \n" +
      "Advisor: For the autumn semester, initial applications closed in May, but late tier placement remains open until July 18th. The security deposit is £450. \n" +
      "Student: Excellent. And does the student union provide subsidized railcards? \n" +
      "Advisor: Yes, the annual tertiary commuter pass is discounted to £68 for full-time scholars. Also, could I have your student identification reference? \n" +
      "Student: Yes, it's PG-99412.",
    questions: [
      {
        id: "lc21-q1",
        questionNumber: 1,
        type: "note_completion",
        prompt: "Late housing application deadline: ______________",
        correctAnswer: "July 18th",
        acceptableAnswers: ["July 18th", "18 July", "July 18", "18th July"],
        transcriptTimestamp: "0:20",
        proofQuote: "...late tier placement remains open until July 18th.",
        distractorTrapExplanation: "The speaker mentions May first as the initial deadline, but the active deadline is July 18th.",
      },
      {
        id: "lc21-q2",
        questionNumber: 2,
        type: "note_completion",
        prompt: "Student ID reference code: ______________",
        correctAnswer: "PG-99412",
        acceptableAnswers: ["PG-99412", "PG99412"],
        transcriptTimestamp: "0:45",
        proofQuote: "Yes, it's PG-99412.",
        distractorTrapExplanation: "Letter-number codes must be recorded exactly as spoken.",
      },
    ],
  },
  {
    id: "listening-c15",
    title: "Community Solar Cooperative Consultation",
    part: 2,
    source: { book: 15, test: 2, section: 2, title: "Renewable Energy Co-op Membership" },
    contextDescription: "A representative explains the installation timeline and financial dividends of a rooftop solar array co-op.",
    speakerAccent: "Australian",
    prepTimeSeconds: 25,
    durationSeconds: 55,
    audioScript:
      "Good afternoon everyone. Our civic solar cooperative has now connected 240 household panels across the suburb. New enrollees pay an initial capital equity share of $350. Quarterly dividend payments commence in October. All inverters come with a standard 10-year warranty, but you can upgrade to 15 years for an additional $75. Maintenance inspections occur biannually, specifically in March and September.",
    questions: [
      {
        id: "lc15-q1",
        questionNumber: 1,
        type: "note_completion",
        prompt: "Initial cooperative equity share cost: $______________",
        correctAnswer: "350",
        acceptableAnswers: ["350", "$350"],
        transcriptTimestamp: "0:22",
        proofQuote: "New enrollees pay an initial capital equity share of $350.",
        distractorTrapExplanation: "Notice 240 is the number of households, while $350 is the share cost.",
      },
    ],
  },
  {
    id: "listening-c10",
    title: "Wildlife Sanctuary Habitat Restoration",
    part: 3,
    source: { book: 10, test: 3, section: 3, title: "Riparian Buffer Zone Assessment" },
    contextDescription: "Two environmental biology students review water turbidity measurements along a restored riverbank.",
    speakerAccent: "British",
    prepTimeSeconds: 30,
    durationSeconds: 58,
    audioScript:
      "Student 1: Looking at the turbidity sensor data from station four, silt runoff dropped by 45 percent once the willow saplings established root networks. \n" +
      "Student 2: That confirms our hypothesis regarding vegetated riparian buffers. However, macroinvertebrate biodiversity didn't rebound until six months later when dissolved oxygen levels stabilized above 8 parts per million.",
    questions: [
      {
        id: "lc10-q1",
        questionNumber: 1,
        type: "note_completion",
        prompt: "Macroinvertebrate biodiversity recovered once dissolved oxygen exceeded ______________ parts per million.",
        correctAnswer: "8",
        acceptableAnswers: ["8", "eight"],
        transcriptTimestamp: "0:38",
        proofQuote: "...until six months later when dissolved oxygen levels stabilized above 8 parts per million.",
        distractorTrapExplanation: "45% was the silt reduction, 6 months was the time lag, 8 was the oxygen threshold.",
      },
    ],
  },
  {
    id: "listening-c1",
    title: "Regional Library Archival Registration",
    part: 1,
    source: { book: 1, test: 1, section: 1, title: "Historical Archives Membership Card" },
    contextDescription: "A visitor registers for an archival research pass at a regional reference library.",
    speakerAccent: "British",
    prepTimeSeconds: 20,
    durationSeconds: 48,
    audioScript:
      "Clerk: Good morning. To issue your researcher pass, I'll need your residential postcode and primary telephone. \n" +
      "Visitor: Certainly, my postal code is CB3 0FA, and my phone number is 01223 765409. \n" +
      "Clerk: And what specific historical manuscript collection will you be consulting? \n" +
      "Visitor: The 19th-century railway maps, catalogue series B.",
    questions: [
      {
        id: "lc1-q1",
        questionNumber: 1,
        type: "note_completion",
        prompt: "Applicant's postal code: ______________",
        correctAnswer: "CB3 0FA",
        acceptableAnswers: ["CB3 0FA", "CB30FA"],
        transcriptTimestamp: "0:18",
        proofQuote: "Certainly, my postal code is CB3 0FA...",
        distractorTrapExplanation: "British postcodes blend letters and numbers; listen carefully to each character.",
      },
    ],
  },
];

// Full Cambridge 1 to 21 Micro-Drill Registry
export const CAMBRIDGE_1_TO_21_MICRO_TRACKS: LessonTrack[] = [
  // ERA 1: LATEST ADVANCED (Cambridge 17 to 21)
  {
    id: "reading-c21",
    bookNumber: 21,
    title: "Cambridge 21: Quantum Cryptography",
    module: "reading",
    subtitle: "Passage 1 • TFNG & Technical Summary Completion",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Mastery (8.5-9.0)",
    cambridgeReference: "Cambridge 21, Test 1, Passage 1",
    description: "Master modern quantum communication terminology and complex contradiction traps.",
  },
  {
    id: "listening-c21",
    bookNumber: 21,
    title: "Cambridge 21: Postgraduate Induction",
    module: "listening",
    subtitle: "Section 1 • Numerical & Deadline Traps",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 21, Test 1, Section 1",
    description: "Detect date and fee distractors during academic student onboarding dialogues.",
  },
  {
    id: "reading-c20",
    bookNumber: 20,
    title: "Cambridge 20: Urban Heat Islands",
    module: "reading",
    subtitle: "Passage 2 • Microclimate Engineering & Cool Pavements",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 20, Test 2, Passage 2",
    description: "Differentiate between theoretical environmental solutions and practical municipal barriers.",
  },
  {
    id: "reading-c19",
    bookNumber: 19,
    title: "Cambridge 19: Deep-Sea Bioluminescence",
    module: "reading",
    subtitle: "Passage 3 • Bathypelagic Ecology & Headings",
    estimatedMinutes: 3,
    xpReward: 40,
    difficulty: "Mastery (8.5-9.0)",
    cambridgeReference: "Cambridge 19, Test 3, Passage 3",
    description: "Navigate dense biological descriptions and identify comprehensive paragraph themes.",
  },
  {
    id: "reading-3",
    bookNumber: 18,
    title: "Cambridge 18: Orca Bioacoustics",
    module: "reading",
    subtitle: "Passage 3 • Dialect Divergence & NOT GIVEN Nuance",
    estimatedMinutes: 3,
    xpReward: 40,
    difficulty: "Mastery (8.5-9.0)",
    cambridgeReference: "Cambridge 18, Test 4, Passage 3",
    description: "Discern the exact boundary between direct textual contradiction and unstated assumptions.",
  },
  {
    id: "reading-1",
    bookNumber: 17,
    title: "Cambridge 17: Silk Road Trade",
    module: "reading",
    subtitle: "Passage 1 • Caravan Networks & Summary Completion",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 17, Test 1, Passage 1",
    description: "Analyze micro-paragraphs for deceptive distractors and direct proof sentences.",
  },
  {
    id: "listening-1",
    bookNumber: 17,
    title: "Cambridge 17: Island Microgrids",
    module: "listening",
    subtitle: "Section 3 • Technical Multiple Choice & Proof Lines",
    estimatedMinutes: 4,
    xpReward: 35,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 17, Test 2, Section 3",
    description: "Track academic discussions between tutor and students without falling for initial opinions.",
  },
  {
    id: "reading-2",
    bookNumber: 16,
    title: "Cambridge 16: Vertical Farming",
    module: "reading",
    subtitle: "Passage 2 • Matching Headings & Negation Traps",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 16, Test 3, Passage 2",
    description: "Differentiate balanced arguments and extreme quantifier traps in CEA technology.",
  },

  // ERA 2: CONTEMPORARY EXAM STANDARDS (Cambridge 11 to 15)
  {
    id: "reading-c15",
    bookNumber: 15,
    title: "Cambridge 15: Deciphering Maya Glyphs",
    module: "reading",
    subtitle: "Passage 1 • Epigraphy & Syllabic Systems",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 15, Test 1, Passage 1",
    description: "Identify linguistic terminology and contrast historical theories with decipherment breakthroughs.",
  },
  {
    id: "listening-c15",
    bookNumber: 15,
    title: "Cambridge 15: Solar Co-op Consultation",
    module: "listening",
    subtitle: "Section 2 • Australian Accent & Numerical Data",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Foundation (5.5-6.5)",
    cambridgeReference: "Cambridge 15, Test 2, Section 2",
    description: "Practice Australian vowels and note-taking with warranty and dividend statistics.",
  },
  {
    id: "reading-c14",
    bookNumber: 14,
    title: "Cambridge 14: Renaissance Cartography",
    module: "reading",
    subtitle: "Passage 2 • Portolan Charts & Mercator Projection",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 14, Test 2, Passage 2",
    description: "Understand navigation historical texts and extract exact two-word geographical phrases.",
  },
  {
    id: "writing-grammar",
    bookNumber: 13,
    title: "Cambridge 13: Inversion Tile Drills",
    module: "writing",
    subtitle: "Track B • Parsons Word Tile Reordering",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 13 Writing Criterion",
    description: "Construct Band 8.5+ negative inversions ('Not only did...') using tactile word tiles.",
  },
  {
    id: "writing-paraphrase",
    bookNumber: 12,
    title: "Cambridge 12: Paraphrase Master",
    module: "writing",
    subtitle: "Track C • Task 1 & 2 Register Upgrades",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Mastery (8.5-9.0)",
    cambridgeReference: "Cambridge 12 Task 1 & 2 Scoring",
    description: "Transform simple prompt sentences into high-scoring academic introductions.",
  },

  // ERA 3: FOUNDATIONAL CORE (Cambridge 6 to 10)
  {
    id: "reading-c10",
    bookNumber: 10,
    title: "Cambridge 10: Stepwells of Western India",
    module: "reading",
    subtitle: "Passage 1 • Architectural Subterranean Sanctuaries",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 10, Test 1, Passage 1",
    description: "Analyze ancient geotechnical engineering and cultural preservation passages.",
  },
  {
    id: "listening-c10",
    bookNumber: 10,
    title: "Cambridge 10: Habitat Restoration",
    module: "listening",
    subtitle: "Section 3 • Riparian Turbidity & Scientific Units",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 10, Test 3, Section 3",
    description: "Extract numerical environmental thresholds while filtering out percentage distractors.",
  },
  {
    id: "writing-spelling",
    bookNumber: 8,
    title: "500 Essential Words: Spelling Mastery",
    module: "writing",
    subtitle: "Track A • 500 High-Frequency Academic Words (19 Packs)",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Foundation (5.5-6.5)",
    cambridgeReference: "Cambridge Common Errors Archive & 500 Lexicon",
    description: "Conquer the 500 most essential IELTS writing words across 19 thematic packs with Azerbaijani meanings and synonyms.",
  },
  {
    id: "writing-synonyms",
    bookNumber: 8,
    title: "500 Academic Synonyms: Avoid Word Repetition",
    module: "writing",
    subtitle: "Track B • Replace Overused Words with Band 8+ Lexis",
    estimatedMinutes: 3,
    xpReward: 35,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge Academic Synonyms & Lexical Resource",
    description: "Master 500 academic synonym upgrades to eliminate repetitive, simplistic vocabulary in IELTS Task 1 & Task 2.",
  },

  // ERA 4: HERITAGE FOUNDATIONS (Cambridge 1 to 5)
  {
    id: "reading-c5",
    bookNumber: 5,
    title: "Cambridge 5: Samuel Johnson's Lexicon",
    module: "reading",
    subtitle: "Passage 2 • Lexicography & Literary Quotations",
    estimatedMinutes: 3,
    xpReward: 30,
    difficulty: "Advanced (7.0-8.0)",
    cambridgeReference: "Cambridge 5, Test 1, Passage 2",
    description: "Study early lexicographical passages and track synonym adaptations across centuries.",
  },
  {
    id: "reading-c1",
    bookNumber: 1,
    title: "Cambridge 1: The Great Stink of London",
    module: "reading",
    subtitle: "Passage 1 • Civil Engineering & Miasma Theory",
    estimatedMinutes: 3,
    xpReward: 25,
    difficulty: "Foundation (5.5-6.5)",
    cambridgeReference: "Cambridge 1, Test 1, Passage 1",
    description: "Examine classic Cambridge Reading formats exploring historical Victorian infrastructure.",
  },
  {
    id: "listening-c1",
    bookNumber: 1,
    title: "Cambridge 1: Historical Library Pass",
    module: "listening",
    subtitle: "Section 1 • Postal Codes & British Digit Formats",
    estimatedMinutes: 2,
    xpReward: 25,
    difficulty: "Foundation (5.5-6.5)",
    cambridgeReference: "Cambridge 1, Test 1, Section 1",
    description: "Master foundational Section 1 telephone numbers and alphanumeric postcodes.",
  },
];
